'use client';

import { Suspense, useEffect, useState } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { CheckCircle2, ReceiptText, ShieldCheck } from 'lucide-react';
import { getReceiptByPaymentId } from '@/lib/paymentStore';

function ReceiptInner() {
  const searchParams = useSearchParams();
  const [receipt, setReceipt] = useState(null);

  useEffect(() => {
    queueMicrotask(() => {
      setReceipt(getReceiptByPaymentId(searchParams.get('id')));
    });
  }, [searchParams]);

  if (!receipt) {
    return (
      <div className="card-medical mx-auto max-w-xl rounded-2xl text-center">
        <ReceiptText className="mx-auto text-surface-400" size={30} />
        <h1 className="mt-3 text-xl font-black text-surface-900">Receipt not available</h1>
        <p className="mt-2 text-sm text-surface-500">Only successful payments generate receipts.</p>
        <Link href="/patient/payments" className="btn-primary mt-5 inline-flex">Back to payments</Link>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-2xl">
      <section className="card-medical overflow-hidden rounded-2xl p-0">
        <div className="bg-primary-600 p-6 text-white">
          <div className="flex items-center justify-between gap-4">
            <div>
              <p className="text-xs font-bold uppercase tracking-wider text-primary-100">CareCuisin receipt</p>
              <h1 className="mt-2 text-2xl font-black">{receipt.receiptNumber}</h1>
            </div>
            <span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/15">
              <CheckCircle2 size={25} />
            </span>
          </div>
        </div>

        <div className="space-y-4 p-6">
          {[
            ['Payment ID', receipt.paymentId],
            ['Provider', receipt.provider],
            ['Reference', receipt.transactionReference],
            ['Description', receipt.description || 'CareCuisin payment'],
            ['Paid at', receipt.paidAt ? new Date(receipt.paidAt).toLocaleString() : 'Recorded'],
          ].map(([label, value]) => (
            <div key={label} className="flex items-center justify-between gap-4 border-b border-surface-100 pb-3 text-sm">
              <span className="font-semibold text-surface-500">{label}</span>
              <span className="text-right font-bold text-surface-900">{value}</span>
            </div>
          ))}

          <div className="rounded-2xl border border-success/20 bg-success/10 p-4">
            <div className="flex items-center gap-2 text-sm font-bold text-success">
              <ShieldCheck size={17} />
              Payment verified
            </div>
            <p className="mt-2 text-xs text-surface-500">This receipt is generated by the CareCuisin payment module and can be reconciled by Admin.</p>
          </div>

          <div className="flex items-center justify-between rounded-2xl bg-surface-50 p-4">
            <span className="text-sm font-semibold text-surface-500">Total paid</span>
            <span className="text-xl font-black text-surface-900">{receipt.amount.toLocaleString()} {receipt.currency}</span>
          </div>

          <Link href="/patient/payments" className="btn-primary inline-flex w-full justify-center">Done</Link>
        </div>
      </section>
    </div>
  );
}

export default function ReceiptPage() {
  return (
    <Suspense fallback={<div className="card-medical mx-auto max-w-2xl rounded-2xl">Loading receipt...</div>}>
      <ReceiptInner />
    </Suspense>
  );
}
